### ISSUE TITLE
Module methods raise AttributeError when passed to help()

### ISSUE THREAD

**Issue by matthewkapfhammer** [20tab/UnrealEnginePython#102]
It doesn't look like this is supposed to work, but I thought I'd bring it up since I kind of expected it to... 
```python
>>> import unreal_engine as ue 
>>> ue.log(help(ue.get_assets_by_filter))
'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "_sitebuiltins.py", line 103, in __call__
  File "pydoc.py", line 1845, in __call__
  File "pydoc.py", line 1898, in help
  File "pydoc.py", line 1632, in doc
  File "pydoc.py", line 1410, in pager
  File "pydoc.py", line 1534, in plainpager
AttributeError: 'NoneType' object has no attribute 'write'
```

What I'm actually after is an example. Is there one that I missed somewhere? 
Thanks!
MK

**Comment by rdeioris** [comment]
Hi, yes we currently do not initialize an emulator sys.stdout and sys.stderr, like we do here:

https://github.com/20tab/UnrealEnginePython/blob/master/tests.py#L14

in addition to this, none of the exposed methods has the help string attached:

https://github.com/20tab/UnrealEnginePython/blob/master/Source/UnrealEnginePython/Private/UEPyModule.cpp#L208

(the last empty string is the doc string, if you want to help pull requests are really welcomed ;)

**Comment by matthewkapfhammer** [comment]
Thanks for the quick reply! I can probably help out with that a bit along with the other examples I mentioned adding before. I'll start replying here once I start.

Can you also provide a quick example of how to use ue.get_assets_by_filter? 

Thanks!
MK
