### ISSUE TITLE
How to apply force to object?

### ISSUE THREAD

**Issue by RepublicofTexas** [20tab/UnrealEnginePython#309]
How do I apply a force to an object? I haven't seen anything on how to do that

**Comment by rdeioris** [comment]
You have access to the whole Blueprint/Reflection api in a pythonic way:

```python
from unreal_engine.classes import StaticMeshComponent
from unreal_engine import FVector

class Pusher:

    def begin_play(self):
        actor = self.uobject.get_owner()
        physical_object = actor.get_actor_component_by_type(StaticMeshComponent)
        physical_object.AddForce(FVector(0, 0, 100000), '', True)
```

**Comment by RepublicofTexas** [comment]
Oh ok nice, thanks a bunch! Another question, if I use a double in python would it work or does it not let me get more decimal accuracy?

**Comment by RepublicofTexas** [comment]
Ah, darn, wanted to use it to get some more precision for a small variable I needed

**Comment by rdeioris** [comment]
what about working with it in python and then casting to string when storing in ue objects ?

**Comment by RepublicofTexas** [comment]
Not sure what you mean by that? Sorry I don't have a big grasp on python, and especially not a big grasp on python and UE4 hehe

**Comment by rdeioris** [comment]
So, internally python uses double for float, while unreal uses float. Whenever you write a python float to an unreal object property (of type float) it will be downcasted to float (so you lose precision). This results in python having bigger precision than unreal.

My suggestion is to not have a FloatProperty in unreal objects but a StringProperty:

```python
# this is a double internally
py_value = 0.0000111

# write to the ue object as string:

uobject.YourStringProperty = str(py_value)

# read back the value:

py_value = float(uobject.YourStringProperty)
```

Not the fastest solution obviously, but should allows you to reach double precision for unreal objects

**Comment by RepublicofTexas** [comment]
Ok I will do that! Thanks a bunch!

**Comment by RepublicofTexas** [comment]
For some reason I get the error 
`
LogPython: Error: invalid value for UProperty
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "../../../../../Users/airma/Documents/Unreal Projects/MyProject8/Content/Scripts\gameclass.py", line 9, in begin_play
    self.uobject.Sphere = str(py_value)
LogPython: Error: ValueError: invalid value for UProperty` With `python
import unreal_engine as ue

class Hero:
    
    # This is called on game start
    def begin_play(self):
        py_value = 0.0000111
        self.uobject.Sphere = str(py_value)
        py_value = float(self.uobject.Sphere)
        ue.log(py_value)
    # This is called every game 'tick'
    def tick(self, delta_time):
        # Get current location
        location = self.uobject.get_actor_location()`

**Comment by rdeioris** [comment]
is Sphere an FString ? note that if you are on python 2 you need to use unicode instead of str

**Comment by RepublicofTexas** [comment]
Sphere is the object I wanted to have an effect on. It's not an FString, I don't think I understand this that well

**Comment by rdeioris** [comment]
You need a property in your Actor/Component/UObject in which you can store the python float as a string

**Comment by RepublicofTexas** [comment]
Ok I'll do that, thanks (again, haha)!

**Comment by RepublicofTexas** [comment]
Ok this is probably a dumb question but how do I make a property? I can't find any documentation on how to make one

**Comment by unbit** [comment]
At this point, are you sure you need to pass those 'double' values back to unreal instead of working only with python ?

**Comment by RepublicofTexas** [comment]
Uhhh I'm fine with working only with python but from what rdeioris said I'm pretty sure it makes itself a float once it reads the variable

**Comment by RepublicofTexas** [comment]
Any way to fix this?

**Comment by rdeioris** [comment]
@RepublicofTexas Hi, i think you need to give us a bit of context, because tecnically i do not see problems in working with doubles from the python side, but it is not clear (at least to me) what you want to do with those numbers into unreal

**Comment by RepublicofTexas** [comment]
I need to make a property for an object but haven't found any documentation on how to, (I want to apply force to a sphere but need a property for the sphere)

**Comment by rdeioris** [comment]
A property is a 'variable' in blueprint naming, just add a variable to your blueprint and then you can access it from python

**Comment by RepublicofTexas** [comment]
Ah okay nice, sorry for confusion!

**Comment by RepublicofTexas** [comment]
```invalid value for UProperty
Traceback (most recent call last):
  File "../../../../../../../Users/myuser/Documents/Unreal Projects/MyProject11/Content/Scripts\m.py", line 8, in begin_play
    self.uobject.Python = str(py_value)
ValueError: invalid value for UProperty``` I get that with a "Python" Component, It's variable name is "Python" And I call it with 
```python
        py_value = 0.00001111
        self.uobject.Python = str(py_value)
        py_value = float(self.uobject.Python)``` Attached is a picture of my full screen of what I have [https://i.imgur.com/tjg7uqy.png](url)

**Comment by RepublicofTexas** [comment]
Nevermind I realized you use a string variable, should've realized that at first! Issue solved!

**Comment by RepublicofTexas** [comment]
Welp seems I have encountered another issue, I'm not finding any more precision. I'm getting an output of 6.67e-11 which is 1 problem solved (Can even have small variables now) but i still can't have it add more precision a.k.a with ```python
import decimal
import unreal_engine as ue

class Hero:
    def begin_play(self):
        py_value = 6.67*10**(-11)
        self.uobject.sad = str(py_value)
        py_value = decimal.Decimal(self.uobject.sad)
        ue.log(py_value)``` I get an output of `6.67E-11` when it should output `0.000000000667`
