### ISSUE TITLE
using python packages such as numpy in linux

### ISSUE THREAD

**Issue by dalietimes** [20tab/UnrealEnginePython#32]
I was able to get this up and running thanks to your latest commit and with the "funnygameclasses.py" used in the readme. The example of moving the sphere at every tick worked fine. However, I'm wondering what the process is for adding other python packages such as numpy in Linux. Here's the error I'm getting from the log:

[2016.10.03-01.13.50:776][717]LogPython:Error: /home/daeil/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct
[2016.10.03-01.13.50:777][717]LogPython:Error: Traceback (most recent call last):

[2016.10.03-01.13.50:777][717]LogPython:Error:   File "../../../../../Projects/Unreal/DeepCars/Content/Scripts/funnygameclasses.py", line 3, in <module>
    import numpy as np

[2016.10.03-01.13.50:777][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs

[2016.10.03-01.13.50:777][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc

[2016.10.03-01.13.50:777][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *

[2016.10.03-01.13.50:777][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx

[2016.10.03-01.13.50:777][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray

[2016.10.03-01.13.50:777][717]LogPython:Error: ImportError: /home/daeil/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct

[2016.10.03-01.13.50:812][717]LogPython:Error: /home/daeil/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct
[2016.10.03-01.13.50:812][717]LogPython:Error: Traceback (most recent call last):

[2016.10.03-01.13.50:812][717]LogPython:Error:   File "../../../../../Projects/Unreal/DeepCars/Content/Scripts/funnygameclasses.py", line 3, in <module>
    import numpy as np

[2016.10.03-01.13.50:812][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs

[2016.10.03-01.13.50:812][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc

[2016.10.03-01.13.50:812][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *

[2016.10.03-01.13.50:812][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx

[2016.10.03-01.13.50:812][717]LogPython:Error:   File "/home/daeil/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray

[2016.10.03-01.13.50:812][717]LogPython:Error: ImportError: /home/daeil/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct

**Comment by sorenvdb** [comment]
So did you solve it?
