### ISSUE TITLE
Recompiling Plugin  on projectLoad fails

### ISSUE THREAD

**Issue by infernalspawn** [20tab/UnrealEnginePython#477]
when attempting to recompile the plugin during loading of the project i'm getting an error message

`[98/220] Compile PyHUD.gen.cpp
1 error generated.
In file included from /vol/dev/src/sebastian/UnrealEngine/testProj01/Plugins/UnrealEnginePython/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UnrealEnginePython/PyNativeWidgetHost.gen.cpp:8:
In file included from /vol/dev/src/sebastian/UnrealEngine/testProj01/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Public/PyNativeWidgetHost.h:6:
In file included from /vol/dev/src/sebastian/UnrealEngine/testProj01/Plugins/UnrealEnginePython/Source/UnrealEnginePython/Public/UnrealEnginePython.h:22:
In file included from /usr/include/python2.7/Python.h:8:
/usr/include/python2.7/pyconfig.h:3:12: fatal error: 'x86_64-linux-gnu/python2.7/pyconfig.h' file not found #  include <x86_64-linux-gnu/python2.7/pyconfig.h>`

the directory/file in that the pyconfig.h is pointing to exists

`/usr/include/x86_64-linux-gnu/python2.7/pyconfig.h`

i'm wondering if there is an include-directory missing somewhere ? 
... using:
- current 'master' - branch 
- UE4.20
- Ubuntu16.04

thanks for your help!

**Comment by rdeioris** [comment]
It looks like in 4.20 Epic added its toolchain, so the python plugin is built with a clang++ different from the system one. Unfortunately the ubuntu python releases require a system-specific pyconfig.h header that is in a directory not added to the includes path of the toolchain. Fast (and dirty) solution would be creating x86_64-linux-gnu/python2.7/pyconfig.h in /usr/include/python2.7 to fake the system

**Comment by rdeioris** [comment]
Another solution would be using an official python releases compiled from sources

**Comment by infernalspawn** [comment]
i've attempted to symlink /x86_64-linux-gnu/ into  /usr/include/python2.7, which seemed to fix that error message, however it is now complaining about re-defined macros, not sure if this is working as expected ;)
/usr/include/python2.7/x86_64-linux-gnu/python2.7/pyconfig.h:1245:9: error: '_XOPEN_SOURCE' macro redefined [-Werror,-Wmacro-redefined]

I'm not sure if i understand correctly with what you mean with 'using an official python releases compiled from sources' ... do you refer to inbuild python in UE 4.20 ? or a prebuild UnrealEnginePython plugin ?

**Comment by rdeioris** [comment]
I have tried the trick with python 3. Eventually add 

#undef _XOPEN_SOURCE

before including Python.h in the code

For official python releases i mean the tar.gz you download from official python site and build with ./configure ; make ; make install

**Comment by slartibaartfast** [comment]
After making a symlink UnrealEnginePython compiled, but now I'm getting errors when I try to import packages like asyncio and numpy.  Is this related or should I open a new issue?

What do you think is the best way to adapt to the new toolchain?  I have ubuntu 18.04 with clang 6.0.0.

For example, here is the error from asyncio that is being loaded from Content/Scripts/AdditionalModules

> [2018.09.13-21.39.14:130][499]LogTemp: >>> import asyncio
[2018.09.13-21.39.14:136][499]LogPython: Error: invalid syntax (_base.py, line 414)
[2018.09.13-21.39.14:142][499]LogPython: Error: Traceback (most recent call last):

[2018.09.13-21.39.14:143][499]LogPython: Error:   File "<string>", line 1, in <module>

[2018.09.13-21.39.14:143][499]LogPython: Error:   File "/usr/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *

[2018.09.13-21.39.14:143][499]LogPython: Error:   File "/usr/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures

[2018.09.13-21.39.14:143][499]LogPython: Error:   File "../../../../../Documents/UnrealProjects/PyMuws/Content/Scripts/AdditionalModules/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,

[2018.09.13-21.39.14:143][499]LogPython: Error:   File "../../../../../Documents/UnrealProjects/PyMuws/Content/Scripts/AdditionalModules/concurrent/futures/_base.py", line 414

[2018.09.13-21.39.14:144][499]LogPython: Error:     raise exception_type, self._exception, self._traceback

[2018.09.13-21.39.14:144][499]LogPython: Error:                         ^

[2018.09.13-21.39.14:144][499]LogPython: Error: SyntaxError: invalid syntax

>

**Comment by rdeioris** [comment]
Hi, it looks like you have some kind of nameclash. Your asyncio import is using the modules in the AdditionalModules/concurrent/futures directory instead of the /usr/lib/python3.6/ one

**Comment by AdamGlass** [comment]
Adding PublicIncludePaths.Add("/usr/include"); makes this work for me and gets me a working plugin.  Maybe the toolchain's include path is being configured so as to override the the std paths completely.
