### ISSUE TITLE
Add Variables on LevelBlueprint

### ISSUE THREAD

**Issue by ricardosferro** [20tab/UnrealEnginePython#558]
Hi Guys,

I need to automate a routine to include variables on my LevelBlueprint through of python, but my routine just works after I click on the button of the blueprint and click on Open Level Blueprint.

For example:
If I execute the code below, it doesn't work, but when Open Level Blueprint and execute the code again, it works.

Please, How can I do this, totally automatized without click on Open Level Blueprint before to execute code?

Code:
import unreal_engine as ue
from unreal_engine.classes import WorldFactory, LevelScriptBlueprint
from unreal_engine.structs import Vector, EdGraphPinType

wiW     = ue.get_editor_world()
wiWLB   = wiW.CurrentLevel.LevelScriptBlueprint

pin = EdGraphPinType(PinCategory='struct',PinSubCategoryObject=Vector)
ue.blueprint_add_member_variable(wiWLB, 'TestVector', pin, None, '17,22,30')

LogError, Before Open Level Blueprint:
LogPython: Error: uobject is not a Blueprint
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 9, in <module>
LogPython: Error: Exception: uobject is not a Blueprint

Thanks,
Guys

**Comment by rdeioris** [comment]
Hi, it is happening because the level blueprint asset is still not loaded in memory.
I have added the get_level_script_blueprint() function to automatically retrieve/load it:

https://github.com/20tab/UnrealEnginePython/blob/master/examples/edit_level_blueprint.py

**Comment by ricardosferro** [comment]
First of all, thanks by helping me...
So, I've been trying with this code, but get_level_script_blueprint(), doesn't work with blueprint level loaded memory too.

Error in get_level_blueprint(): line 5
level_bp = world.CurrentLevel.get_level_script_blueprint()

Output Log
LogPython: Error: 'unreal_engine.UObject' object has no attribute 'get_level_script_blueprint'
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 5, in <module>
LogPython: Error: AttributeError: 'unreal_engine.UObject' object has no attribute 'get_level_script_blueprint'

![image](https://user-images.githubusercontent.com/11772229/47572021-e09fe400-d931-11e8-8607-1274912e94bc.png)

**Comment by rdeioris** [comment]
Arey ou using the latest version of the plugin ?

**Comment by ricardosferro** [comment]
This version, because it is embedded...  
20180907_4_20_python36_embedded_win64
