### ISSUE TITLE
All unit tests fail on macOS

### ISSUE THREAD

**Issue by Pepin-** [20tab/UnrealEnginePython#63]
On Sierra, recent changes have gotten the plugin to successfully compile (using Python 3.5.2, UE 4.13, threading support disabled).

But running the unit tests cause the editor to crash:

If I comment out
`self.uobject.quit_game()`
from tests.py

Then I get the following output:

```
PlayLevel: No blueprints needed recompiling
New page: SIE session: MainLevel (Oct 23, 2016, 11:05:51 PM)
Creating play world package: /Game/UEDPIE_0_MainLevel
PIE: StaticDuplicateObject took: (0.002017s)
Creating AISystem for world MainLevel
Got a bulk data texture, with 1 mips
PIE: World Init took: (0.000700s)
Got a bulk data texture, with 1 mips
PIE: Created PIE world by copying editor world from /Game/MainLevel.MainLevel to /Game/UEDPIE_0_MainLevel.MainLevel (0.003290s)
Got a bulk data texture, with 1 mips
FAudioDevice initialized.
Game class is 'GameMode'
Bringing World /Game/UEDPIE_0_MainLevel.MainLevel up for play (max tick rate 0) at 2016.10.24-03.05.51
Bringing up level for play took: 0.001412
Native class hierarchy updated for 'MovieSceneCapture' in 0.0018 seconds. Added 11 classes and 0 folders.
Match State Changed from EnteringMap to WaitingToStart
F
F
.
F
======================================================================
FAIL: test_create_player (tests.TestPlayer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../../../../../../Pepin/Dropbox/ETC/Fall 2016/Cozplay/Final Unity Setup/Unreal mk2/Test2/Content/Scripts/tests.py", line 45, in test_create_player
    self.assertEqual(self.actor.get_num_players(), 1)
AssertionError: 0 != 1
======================================================================
FAIL: test_location (tests.TestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../../../../../../Pepin/Dropbox/ETC/Fall 2016/Cozplay/Final Unity Setup/Unreal mk2/Test2/Content/Scripts/tests.py", line 26, in test_location
    self.assertEqual(location, (1, 1, 1))
AssertionError: <unreal_engine.FVector object at 0x179c65790> != (1, 1, 1)
======================================================================
FAIL: test_scale (tests.TestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../../../../../../Pepin/Dropbox/ETC/Fall 2016/Cozplay/Final Unity Setup/Unreal mk2/Test2/Content/Scripts/tests.py", line 38, in test_scale
    self.assertEqual(scale, (3, 5, 7))
AssertionError: <unreal_engine.FVector object at 0x179c65790> != (3, 5, 7)
----------------------------------------------------------------------
Ran 4 tests in 0.001s
FAILED
 (failures=3)
Match State Changed from EnteringMap to WaitingToStart
Info Play in editor start time for /Game/UEDPIE_0_MainLevel 0.499
```

Any ideas what could be going on?

**Comment by rdeioris** [comment]
We are working on the new test suite, it should be out soon

**Comment by rdeioris** [comment]
New test suite has been released:  https://github.com/20tab/UnrealEnginePython#unit-testing
