### ISSUE TITLE
FRawMesh is not valid or fixable

### ISSUE THREAD

**Issue by samghafari** [20tab/UnrealEnginePython#813]
I am trying both examples 
StaticMesh: Centering pivot
StaticMesh: Adding LODs

UnrealEnginePython/tutorials/SnippetsForStaticAndSkeletalMeshes.md 

without changing anything, but I get error

FRawMesh is not valid or fixable
Traceback (most recent call last):
  File "Scripts/pivot.py", line 56, in <module>
    add_lods(uobject)
  File "Scripts/pivot.py", line 37, in add_lods
    raw_mesh.save_to_static_mesh_source_model(lod1)
Exception: FRawMesh is not valid or fixable

it seems it has problem with raw_mesh.save_to_static_mesh_source_model, anyone knows the solutions?

**Comment by samghafari** [comment]
@rdeioris is there any solution for this?
